### ISSUE TITLE
Limit elements to one per line not working

### ISSUE THREAD

**Issue by tlhintoq** [Xavalon/XamlStyler#90] opened 2017-01-28 11:10 UTC
Options:
• Attribute Tolerance: 0 - Hint says "A value of less than 1 means always break up the attributes"
• Max attributes per line: 1
Should give you one attribute per line. This is previous version in VS2015
```xml
<Label Text="{Binding Dob,
                      StringFormat='{0:ddMMMyy}'}"
        Style="{StaticResource LabelStyleMed}" />

```
However this version in 2017 seems to not be working the same.
Take a line such as
`Text="{Binding Source={x:Reference this}, Path=Value, Mode=TwoWay}"`
It keeps rearranging to a single line instead of
```xml
Text="{Binding Source={x:Reference this}, 
               Path=Value, 
               Mode=TwoWay}"
```

**Comment by NicoVermeir** [comment] 2017-07-17 09:52
@tlhintoq try removing Binding from the list of Markup Extensions that should be kept on one line in the XAML Styler settings

![image](https://user-images.githubusercontent.com/3177418/28263255-56b9f308-6ae6-11e7-94a5-e0901abec042.png)

**Comment by grochocki** [comment] 2017-09-07 06:26
Resolving, since not a bug. See documentation for more information about [Attribute Tolerance](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#attribute-tolerance) and [Newline Exemption Elements](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#newline-exemption-elements)

**Closed by grochocki** 2017-09-07 06:26 UTC
Labels: Type: Question
