### ISSUE TITLE
Save all / Style all xaml

### ISSUE THREAD

**Issue by Moryerg** [Xavalon/XamlStyler#350] opened 2021-09-23 14:14 UTC
Create a Save all function that style all xaml files in a solution, when Save all button is hit in Visual Studio. Make it optional whether the function is activated on the Save all button, a shortcut or both. 

We have considered to use the batch file solution that already exist, but it takes more to make it work and it's complicated to implement in a team solution.

**Comment by grochocki** [comment] 2021-09-26 05:29
Thanks for the suggestion! This looks like a possible duplicate of #56, where we added support for formatting entire projects and solutions:

![image](https://user-images.githubusercontent.com/1414423/134794899-222421e2-3896-4e69-99ed-69a8ab9a99e7.png)

**Comment by grochocki** [comment] 2023-12-28 20:44
With the ability to format all XAML files within a solution/project, I think that meets the spirit of the original feature request here, so closing. Of course, if there is an improvement to the new feature that we should consider, we can revisit.

**Closed by grochocki** 2023-12-28 20:44 UTC
Labels: Feature
