### ISSUE TITLE
Add support for avalonia (.axaml) files.

### ISSUE THREAD

**Issue by chkr1011** [Xavalon/XamlStyler#320] opened 2021-01-30 13:23 UTC
Since avalonia (https://avaloniaui.net) also uses custom XAML files it would be great if this extension is also able to format that files too. 

The only difference is that these files have a different file extension (.axaml instead of .xaml).

I will also create a pull request for this feature.

**Comment by grochocki** [comment] 2021-01-31 22:37
Thanks for your contribution! This seems to be a duplicate of #300, so closing this issue to continue the conversation there.

**Closed by grochocki** 2021-01-31 22:37 UTC
Labels: Feature
