### ISSUE TITLE
Add a 'Generate Settings.XamlStyler file from settings' button in the Options

### ISSUE THREAD

**Issue by sonnemaf** [Xavalon/XamlStyler#165] opened 2018-11-05 11:44 UTC
It would be nice if there was an 'Generate Settings.XamlStyler file from settings' button in the Options dialog. Similar to the 'Generate .editorconfig file from settings' button in VS2019.

**Comment by grochocki** [comment] 2018-11-11 19:58
Great idea! Closing as duplicate of #60, which captures the same spirit of this. Added a note that implementation might be better in VS options as opposed to standalone.

**Closed by grochocki** 2018-11-11 19:58 UTC
Labels: Type: Feature, ~duplicate
