### ISSUE TITLE
Formatting issue when using <LineBreak/> in content

### ISSUE THREAD

**Issue by Smallgiil** [Xavalon/XamlStyler#513] opened 2024-10-02 13:01 UTC
**Describe the bug**
When I use <LineBreak/> in the content of my XAML element, XAML Styler stops writting the closing tag on a new line. Instead, it appends it right after the content, on the same line.

**To Reproduce**

1. Take following XAML content:
```
<TextBlock Margin="2">
    First line.<LineBreak />
    Second line.
</TextBlock>
```
2. Save the file with the default XAML Styler configuration.
3. See that we get this result:
```
<TextBlock Margin="2">
    First line.<LineBreak />
    Second line.</TextBlock>
```
4. Remove the <LineBreak/> element in the content.
5. Save again.
6. See that you get a different result:
```
<TextBlock Margin="2">
    First line.
    Second line.
</TextBlock>
```

**Expected behavior**

We should get the same result, whether we use <LineBreak/> elements or not.

**External Configuration**

[Settings.XamlStyler.json](https://github.com/user-attachments/files/17229640/Settings.XamlStyler.json)

**Version Info (please complete the following information):**
 - OS: Windows 10 Version 22H2 Build 19045.4894
 - Visual Studio: Professional 17.12.0 Preview 1
 - XAML Styler: 3.2404.2

**Comment by Smallgiil** [comment] 2024-10-02 13:03
Note that `xml:space="preserve"` fixes the issue but changes the behavior.

**Comment by grochocki** [comment] 2024-10-04 07:14
This _appears_ to be a dupe of #510. Closing to continue the discussion there, but if I am mistaken and this is different, we can reopen.

**Closed** 2024-10-04 07:15 UTC
Labels: Bug, ~duplicate, Universal
