### ISSUE TITLE
Error to edit .csproj files on VS 17.9.0

### ISSUE THREAD

**Issue by eder-em** [Xavalon/XamlStyler#470] opened 2024-02-14 15:20 UTC
1. When editing a .csproj file and press save. I started getting the error that you can see on the screenshot below.
2. I noticed the error it started to show up after I've installed the latest version of VS 2022 version 17.9.0

**Screenshots**
<img width="332" alt="image" src="https://github.com/Xavalon/XamlStyler/assets/138801357/197717c6-c1bb-4961-a07b-df4c62f12bb9">

**External Configuration**
If you are using an external configuration, please attach to help reproduce the issue.

**Version Info (please complete the following information):**
 - OS: Windows 11 23H2
 - Visual Studio: 17.9
 - XAML Styler: 3.2311.2

**Comment by SalimiHabib** [comment] 2024-02-27 19:43
Same problem and totally damage .csproj and manifest in MAUI( both in android an windows platform )
it damage my project totally

**Comment by khdc** [comment] 2024-02-29 19:23
This is a weird issue. I can't reproduce it when running XamlStyler in debug mode. But with the latest release version I get the error.

**Comment by grochocki** [comment] 2024-04-03 01:22
I am investigating a blocking issue with the release build of the extension for VS2022 that is preventing it from loading properly. Unfortunately, I am not unable to deploy the extension under debug, blocking progress (#479). The reported issue is fixed by #453, which will be included in that upcoming release, so closing this issue.

**Closed by grochocki** 2024-04-03 01:22 UTC
Labels: Bug

**Comment by eder-em** [comment] 2024-04-04 01:17
Thank you @grochocki and congrats for the amazing extension you guys have created.❤️
