### ISSUE TITLE
Exported settings vs Expected external settings

### ISSUE THREAD

**Issue by ScottIsAFool** [Xavalon/XamlStyler#59] opened 2016-10-28 22:24 UTC
Currently, there seems to be a massive disconnect between the settings that are exported from VS, and the external configuration file that the plugin expects. 
- For a start, VS exports the settings in XML, yet the external config file expects JSON.
- The settings that are exported, don't match what's expected. For example, AttributeIndentationStyle exports as "spaces", external config file expects 2.
- AttributeOrderingRuleGroups exported as a literal dump of the attributes, expected is a list of the different rows.

Is there another way to export this? Or do I have to a) manually create this file and put all the settings in, and b) go through the code to find the corresponding enum values for some of the settings?

**Comment by grochocki** [comment] 2016-11-01 05:44
> For a start, VS exports the settings in XML, yet the external config file expects JSON.

> The settings that are exported, don't match what's expected. For example, AttributeIndentationStyle exports as "spaces", external config file expects 2.

> AttributeOrderingRuleGroups exported as a literal dump of the attributes, expected is a list of the different rows.

This is by design. We do not have any control over the VS import/export mechanics and not as much control as we would like over the output format. The VS feature to import/export features should be used for backing up local settings.

> Is there another way to export this? Or do I have to a) manually create this file and put all the settings in, and b) go through the code to find the corresponding enum values for some of the settings?

Check out the Wiki page on [External Configurations](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations)! It includes a complete configuration with the default options as well as a recently added [mapping of enums](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations#default-configuration-options).

Do you think the information in the Wiki is sufficient or would a feature to generate a JSON configuration be useful?

**Comment by ScottIsAFool** [comment] 2016-11-01 07:28
My bad, for some reason, I completely missed the enum mappings :s

I still think a feature to generate the json would be useful though. If I've made a bunch of changes in VS, I then have to go through and make those changes again manually in my file.

**Comment by grochocki** [comment] 2016-11-01 08:05
> My bad, for some reason, I completely missed the enum mappings

You made a good point about it not being super clear, so I just added it to make it easier :)

**Comment by ScottIsAFool** [comment] 2016-11-01 08:06
@grochocki ahh, I thought I'd been completely blind and not seen them when I originally looked :D

**Comment by grochocki** [comment] 2016-12-13 07:21
Ability to easily generate a JSON configuration is covered by #60. As current behavior is otherwise by design, closing discussion on this topic for now.

**Closed by grochocki** 2016-12-13 07:21 UTC
Labels: Type: Question
