### ISSUE TITLE
Error in StylerPackage (regarding &)

### ISSUE THREAD

**Issue by administersoftware** [Xavalon/XamlStyler#449] opened 2023-11-22 10:56 UTC
In my WPF XAML I'm trying to set a ToolTip="URL & ID", but when saving XamlStyler doesn't seem to like the & and comes up with the following:

![image](https://github.com/Xavalon/XamlStyler/assets/6171720/69d4586d-1f37-4cf2-a92b-c245ce983c43)

**Version Info:**
 - OS: Windows 10 Pro 22H2 19045.3693
 - Visual Studio: VS2022 17.8.0
 - XAML Styler: 3.2311.2

Colin.

**Comment by grochocki** [comment] 2023-12-13 09:09
This seems to be an instance of leveraging a XML character entity. In this case, you should use ```&amp;``` to encode the ampersand in ```ToolTip```.

Dupe of #284. This is a possible candidate for surfacing in some sort of error/warning UI in the future as part of #271, but this is otherwise by design due to XAML language spec. Here is some more information on [XML Character Entities and XAML](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/xaml-services/xml-character-entities).

**Closed by grochocki** 2023-12-13 09:09 UTC
Labels: Bug, ~by design, VS2022
