### ISSUE TITLE
XAML Styler causes Visual Studio 16.4 to freeze when saving all files.

### ISSUE THREAD

**Issue by LoriBru** [Xavalon/XamlStyler#229] opened 2019-12-11 12:57 UTC
It looks like this extension introduces an issue with Visual Studio 16.4. When hitting the "Save All" button on the toolbar, VS freezes completely and must be killed from task manager.
See this discussion regarding the issue:
https://developercommunity.visualstudio.com/content/problem/846793/visual-stidio-1640-freezes-when-save-all-files-via.html?childToView=852709#comment-852709

**Comment by grochocki** [comment] 2019-12-12 22:47
This seems to be a dupe of #216. I am not able to repro the freeze, but can you help validate the change by testing the [Pipelines output from that build](https://dev.azure.com/xavalon/XAML%20Styler/_build/results?buildId=113). This fix (and other recent changes) will be part of 3.3 update, which we hope to publish soon.

**Comment by andrew-baylis** [comment] 2019-12-15 22:56
Note that the freeze happens irrespective of the Format XAML on save setting. 
I have just downloaded and built the latest code commit (173c7f1) and when Format XAML on save is false, the Save All doesn't cause a freeze. Seems to be OK when set true but will need to experiment a bit more.

**Comment by grochocki** [comment] 2019-12-31 21:29
Should be addressed in [3.1912.9](https://github.com/Xavalon/XamlStyler/releases/tag/Release-3.1912.9), available now!

**Closed by grochocki** 2019-12-31 21:29 UTC
Labels: Bug, ~duplicate

**Comment by luisruizlatic** [comment] 2020-02-16 04:50
I have the version 3.2 and still happening.

**Comment by leonbohmann** [comment] 2022-08-02 09:26
Still happening to me with Preview 2022.
