### ISSUE TITLE
Unintended xaml edits

### ISSUE THREAD

**Issue by yohny** [Xavalon/XamlStyler#131] opened 2017-11-30 07:48 UTC
Hello,
I have recently installed XamlStyler (v3.1) into VS2017 (v15.4.5) and I noticed a strange behavior since. Xaml files in solution keep beiing reformatted even if I dont open+save them. The changes correspond to xaml styler settings.  I would expect that only the files I open and save are reformatted. Is there some solution-wide xaml-reformatting going on in backgroud? I did not notice this behavior in VS2015. The solution-wide xaml reformattig happens after I hit save-all button (even if i have no edited files) or when I request solution rebuild (i guess this implies solution-wide save before it).
BTW: this is not isolated case, another team-members are experiencing this too

**Comment by Paradoxon101** [comment] 2018-02-03 11:55
With version 3.0 I didn't have the problem, since version 3.1 it's always comes if i hit "save all"!

**Comment by grochocki** [comment] 2018-10-21 21:42
Duplicate of #142

**Closed by grochocki** 2018-10-21 21:42 UTC
Labels: Type: Bug, ~duplicate
