### ISSUE TITLE
Extension Drastically Impacts VS2019 Stability

### ISSUE THREAD

**Issue by jamsoft** [Xavalon/XamlStyler#318] opened 2021-01-23 12:49 UTC
**Describe the bug**
I installed the extension 5 hours ago and I have just had to disable it.

As soon as it was installed VS was demonstrably less stable. Crashing repeatedly whereas for the last 12 month or so I have had a pretty error free experience with VS2019

After having uninstalled XamlStyler VS is back to its stable self.

I'm wondering if there is an issue with having ReShaper running as well?

It also seemed to happen when my powerline network adaptors had a hiccup. Could this be network related?

**To Reproduce**
1. Install the extension and write some XAML

**Expected behavior**

The plugin should not so severely impact VS.

**Screenshots**

**Version Info (please complete the following information):**
 - OS: [e.g. Windows 10 (2004)
 - Visual Studio: VS2019 (16.8.4)
 - XAML Styler: 3.2008.4

**Additional context**

Unfortunately, VS just bombs and I haven't found any logs.

**Comment by NicoVermeir** [comment] 2021-01-25 06:34
hmm can't say I've seen any of the issues you describe. I'm also running ReSharper.
Could you provide a list of all your installed extensions? Did you only see the issue in XAML - based projects? could you for example try in a command line or asp.net project?

thanks for your help in narrowing this down!

**Comment by grochocki** [comment] 2023-12-28 20:30
I am still unable to reproduce this in VS2019. Closing this issue for now, but if this persists for you with the latest release of the extension, if there is any additional information you can share to help the investigation, that would be super helpful!

**Closed by grochocki** 2023-12-28 20:30 UTC
Labels: Bug, ~no repro, VS2019, needs more info
