### ISSUE TITLE
Use of XAML Styler Configuration

### ISSUE THREAD

**Issue by Depechie** [Xavalon/XamlStyler#185] opened 2019-05-27 06:34 UTC
VS for Mac v8.0.8
XAML Styler v1.1.2

We tried creating an uniform XAML styler settings file for the solution, but did not have much luck on getting this to work.
Is there a sample project we can load to see if we did not make any mistakes?

Also checking the Search to drives root will always be auto checked off again if you close and reopen the Preferences window.

**Comment by Saratsin** [comment] 2019-06-01 17:59
Started to investigate it. Settings file logic is stored inside core project, so maybe the problem is in different file systems between Windows and MacOS. For now I blocked with the problem, that I just can't debug the extension with Visual Studio for Mac. I'll write about it to Microsoft team, maybe they'll help why extension is not debuggable now

**Comment by Saratsin** [comment] 2019-07-02 07:44
@Depechie can you check the new version? This issue should be fixed by PR #194 
New version from this PR is already available on MonoDevelop repository (version 1.1.3)

**Comment by Saratsin** [comment] 2019-07-24 14:23
@Depechie try the new version. It should work correctly on the latest Visual Studio for Mac. Also it should take the Settings.XamlStyler configurations (if this file/files persists inside the solution folder or its subfolders). New version is 1.1.4, it's available in MonoDevelop repository now

**Comment by Depechie** [comment] 2019-07-24 20:16
@Saratsin ok thx… did not yet have time to try it out myself. But will recheck later with the 1.1.4 update.

**Comment by grochocki** [comment] 2019-07-25 22:56
Implemented by #194

**Closed by grochocki** 2019-07-25 22:56 UTC
Labels: Bug, VSMAC
