### ISSUE TITLE
External configuration file resetting

### ISSUE THREAD

**Issue by edcwhite** [Xavalon/XamlStyler#177] opened 2019-02-08 13:32 UTC
In one of the recent releases (works in 3.1) the external configuration file location is now randomly cleared causing the configuration to reset back to default.   We are needing to reset this file location several times a day and it is causing much grief on our project with 20 developers.    A fix would be very much appreciated.

**Comment by grochocki** [comment] 2019-02-08 20:40
The option getting reset definitely sounds like a possible regression, but for team environments, it is generally a lot easier to rely on putting the configuration file in the project repo and letting XAML Styler pick it up automatically without having to manually specify a file path.

**Comment by edcwhite** [comment] 2019-02-13 15:59
I tried that but it doesn't work well for us since many of our projects exist in folders outside of our solution folder path.

**Comment by grochocki** [comment] 2019-02-14 08:17
Have you tried the new [Search to Drive Root](https://github.com/Xavalon/XamlStyler/wiki/XAML-Styler-Configuration#search-to-drive-root) feature in 3.2?

**Comment by jfevia** [comment] 2019-02-14 11:44
I'm upvoting this issue. It has become too much of a hassle after the update for everyone. I have a combination of personal and team projects and all of them are facing the same problem.

I'm disabling the extension until the configuration is loaded properly. Alternatively, I'll just revert to an old version.

**Comment by NicoVermeir** [comment] 2019-02-14 20:20
is this happening in VS2017 and VS2019?

**Comment by jfevia** [comment] 2019-02-15 21:27
@NicoVermeir This is happening in all my VS2017 setups. I haven't tried VS2019 yet.

**Comment by NicoVermeir** [comment] 2019-02-25 08:04
I've been trying to reproduce this but haven't been able to so far. Does anyone have a lead or a clue as to when the path gets reset? maybe a specific action / project type that triggers it?

**Comment by tmatz** [comment] 2019-02-25 08:55
maybe #160

**Comment by GreatFireWall** [comment] 2019-03-02 13:49
same problem.

**Comment by grochocki** [comment] 2019-03-17 07:11
I have been trying to repro this in VS2017 without any luck. I have tried "tricking" it a few different ways by having multiple configurations at different file locations to see if it would try to pick up one of those alternative configurations, but it seems to stick to the one set in settings, as expected.

Can someone who _can_ reproduce the problem try debugging to identify where it might be getting reset?

**Comment by jfevia** [comment] 2019-03-17 07:45
This happens to me on a daily basis. However, yesterday I noticed that I had changed only a reference in App.xaml.

App.xaml
`<Application x:Class="Product.Windows.Client.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:client="clr-namespace:SyncData.Windows.Client"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:ignore="http://www.galasoft.ch/ignore"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d ignore">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Product.Windows.Themes;component/System.Windows.Controls.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <client:ViewModelLocator x:Key="Locator"
                                     d:IsDataSource="True" />
        </ResourceDictionary>
    </Application.Resources>
</Application>`

At the time, `<ResourceDictionary Source="/Product.Windows.Themes;component/System.Windows.Controls.xaml" />` contained an invalid reference. Right after changing this, the configuration was reset and I had to reload it from *.vssettings.

**Comment by grochocki** [comment] 2019-03-17 07:54
Hmmm, I think this _might_ be a red herring, but it is impossible for me to say for sure, though, until someone can repro under debugger. The contents of XAML files should have not have any effect on the extension loading or configuration options. We do not actually validate any references/cross-file/project settings while formatting.

**Comment by GreatFireWall** [comment] 2019-03-17 08:09
It may be that some strings in XML that cause Styler crashing, then the configuration loss. 🤔

**Comment by grochocki** [comment] 2019-03-17 08:11
Definitely a possibility. I tried copying in and formatting @jfevia's code without any crashes. If we can find a block of code that can reliably trigger a reset, that would be a huge help.

**Comment by grochocki** [comment] 2019-09-12 06:48
We discovered in #202 that a syntax error in the configuration file was at fault. This suggests we may have inadvertently fixed a bug in parsing that results in settings being reset. Can folks post their configuration files here to help debug further?

**Comment by jfevia** [comment] 2019-10-04 14:35
Sorry, unfortunately, I no longer have access to the projects used to reproduce this problem.

**Comment by grochocki** [comment] 2019-10-24 00:14
Ok, thanks -- since I am unable to reproduce this issue, I am going to close it as such. Happy to revisit if we find a repro.

**Closed by grochocki** 2019-10-24 00:14 UTC
Labels: Bug, VS2017, needs more info

**Comment by original-dron** [comment] 2020-10-30 06:41
I have this issue.  Strangely a year later.  Using v.3.2008.4.  Happens if "External configuration file" is set or not.  If "Search to drives root" set to true, then set "Reset to default" to true they both flip to false.
