### ISSUE TITLE
Formatting complex attributes paired with plain text

### ISSUE THREAD

**Issue by robsen** [Xavalon/XamlStyler#261] opened 2020-03-22 11:25 UTC
**Describe the bug**
Mismatch of plain text and elements inside a property element as following XAML code demonstrates:
```xaml
<TextBlock>
    Hello,<Run FontWeight="Bold" Text="World" />
    !</TextBlock>
```

**To Reproduce**
1. Copy and paste above code into any WPF project XAML-file.
2. Save file or right click into Visual Studios code-editor and click on "Format XAML", so the XamlStyler will do the formatting.
3. Now the formated XAML code should still look the same. And that's - I guess - not as intended to be.

**Expected behavior**
XamlStyler should format each plain text in it's own row as following code demonstrates.
Element formatting is working fine as expected.
```xaml
<TextBlock>
    Hello,
    <Run FontWeight="Bold" Text="World" />
    !
</TextBlock>
```

**Screenshots**
No screenshots needed.

**External Configuration**
No external configuration used.
My XamlStyler settings are set to plain default. Just installed the Visual Studio 2019 plugin and have had a great time so far. 👍 

**Version Info (please complete the following information):**
 - OS: Windows 10 Pro Version 1809 (Build 17763.914)
 - Visual Studio: VS Pro 2019 (16.4.6)
 - XAML Styler: Extension (3.2001.0)

**Additional context**
Not sure if it's a bug or a feature request. But my feelings say, it's not working as intended - so properly a bug.

**Comment by grochocki** [comment] 2020-03-23 02:46
Thank you for the detailed description! Please take a look at this section of the wiki on how we handle [whitespace](https://github.com/Xavalon/XamlStyler/wiki/Getting-Started#whitespace). There is this concept of "significant whitespace" in XAML that we need to maintain when formatting.

> XamlStyler should format each plain text in it's own row as following code demonstrates.

If we do this, we might inadvertently _add_ whitespace where it wasn't previously. If you are mixing [inline-level flow content elements](https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inline) with other text, you may need to specify xml:space="preserve" to preserve whitespace properly.

If this makes sense and sounds like what you are experiencing, I would like to close this as by design. If not, happy to dig in a bit more to understand how what you are describing is different.

**Comment by robsen** [comment] 2020-03-23 20:17
I guess you can close this issue as by design.
I even didn't realized, that my example does add a space between <Run /> and exclamation mark.

Goal for rendering was as followed:
Hello, **World**!

But the submited code rendered as followed:
Hello, **World** !

So I guess the only right way to do such kind of formatting within a TextBlock is:
```xaml
<TextBlock xml:space="preserve">Hello<Run FontWeight="Bold" Text=" World" />!</TextBlock>
```

Maybe there are better - more readable - ways to achieve this, but I'm pretty new to WPF and not aware of any.

Thanks for clarifying!

**Comment by grochocki** [comment] 2020-03-24 00:21
Another way to do it would be to build it up in code behind. I have done this before for particularly complex text runs, but it is not anymore readable.

**Closed by grochocki** 2020-03-24 00:21 UTC
Labels: Bug
