### ISSUE TITLE
XAML Styler as global tool

### ISSUE THREAD

**Issue by Tyrrrz** [Xavalon/XamlStyler#218] opened 2019-11-20 15:45 UTC
First of all, I want to say MASSIVE THANKS to all the developers and maintainers of this project. I have quite a few XAML-based projects and this extension helps me not hate my life as much.

That said, I'm trying to ditch Visual Studio and, believe it or not, this extension is the only reason that I can't fully commit to that.

Looking through the repository I can see that there's a console app, but is there/have you considered making a global tool? That way XAML Styler could be installed on a per-project basis and ran on all *.xaml files on build. This would also make it compatible with VS Code, Rider, etc.

If you think this is worth the effort, I will help in whichever way I can.

**Comment by grochocki** [comment] 2019-12-02 03:49
Thanks for those kind words! The console app is intended to be used wherever you might need it -- here are some [examples](https://github.com/Xavalon/XamlStyler/wiki/Script-Integration) of how to leverage the console app in scripts. Also, #217 aims to enable the console app to run cross-platform, which helps make it even more universal. Did you have something else in mind?

**Comment by Tyrrrz** [comment] 2019-12-02 08:17
Yeah, I was thinking of possibly publishing the console app, once it's x-platform, as a global tool. That would mean you would be able to run it through `dotnet` CLI.

https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create

**Comment by grochocki** [comment] 2019-12-02 08:40
Sounds good to me! I think the cross-platform part is covered by #219 and the tooling/publishing side of things will be covered by #224. If you agree, I'd like to close this issue as a dupe of those two. Thoughts?

**Comment by Tyrrrz** [comment] 2019-12-02 08:47
Yeah sure. As long as the end result will be a tool that I can install via `dotnet tool install xamlstyler`, I'm happy :)

**Closed** 2019-12-02 08:47 UTC
Labels: Console, needs more info

**Comment by grochocki** [comment] 2020-01-02 23:46
Adding to index: natemcmaster/dotnet-tools#178

**Comment by Tyrrrz** [comment] 2020-01-09 21:02
Made [a little post about it](https://tyrrrz.me/blog/formatting-xaml-on-build). It can serve as a tutorial. :)
