### ISSUE TITLE
Standalone XAMLStyler not available for Mac

### ISSUE THREAD

**Issue by developering** [Xavalon/XamlStyler#197] opened 2019-07-09 15:34 UTC
Unless I'm missing it, I only see a standalone version available for Windows. Is there a way to compile it for Mac as well? I want to setup a git hook for a project that has Windows and MacOS developers, but am unable to do so because of this issue.

**Comment by grochocki** [comment] 2019-07-09 17:13
The standalone executable was PC only as the plugin was too up until very recently when we added support for Visual Studio for Mac. I think it would be awesome to add Mac support to the XamlStyler.Console.

**Comment by developering** [comment] 2019-07-10 14:44
Thanks @grochocki, I thought that might be the case. Appreciate the response!

**Comment by grochocki** [comment] 2019-12-31 21:32
Duplicate of #219. Addressed in [3.1912.9](https://github.com/Xavalon/XamlStyler/releases/tag/Release-3.1912.9), available now!

**Closed by grochocki** 2019-12-31 21:32 UTC
Labels: Console, Feature
