### ISSUE TITLE
Reordering of Namespaces

### ISSUE THREAD

**Issue by jur007** [Xavalon/XamlStyler#106] opened 2017-06-28 13:43 UTC
Everytime I click on "Format XAML" in the VS2017 context menu, the namespaces in the xaml file get reordered. I click again and a 3rd "version" of namespace order appears. No matter how often I click, I never come back to "unchanged" status for svn.

Until this bug is alive, can I disable the ns-ordering?

**Comment by grochocki** [comment] 2017-06-28 18:24
I am not able to reproduce the issue. Are the namespaces _actually_ reordering, or is SVN just _detecting_ a change?

**Comment by jur007** [comment] 2017-06-29 08:11
They are reordering with some variations, so no back and forth, 3 or more layouts.
`{
    "AttributesTolerance": 1,
    "KeepFirstAttributeOnSameLine": true,
    "MaxAttributeCharatersPerLine": 0,
    "MaxAttributesPerLine": 1,
    "NewlineExemptionElements": "RadialGradientBrush, GradientStop, LinearGradientBrush, ScaleTransfom, SkewTransform, RotateTransform, TranslateTransform, Trigger, Condition, Setter",
    "SeparateByGroups": false,
    "AttributeIndentation": 0,
    "AttributeIndentationStyle": 1,
    "RemoveDesignTimeReferences":  false,
    "EnableAttributeReordering": true,
    "AttributeOrderingRuleGroups": [
        "x:Class",
        "xmlns, xmlns:x",
        "xmlns:*",
        "x:Key, Key, x:Name, Name, x:Uid, Uid, Title",
        "Grid.Row, Grid.RowSpan, Grid.Column, Grid.ColumnSpan, Canvas.Left, Canvas.Top, Canvas.Right, Canvas.Bottom",
        "Width, Height, MinWidth, MinHeight, MaxWidth, MaxHeight",
        "Margin, Padding, HorizontalAlignment, VerticalAlignment, HorizontalContentAlignment, VerticalContentAlignment, Panel.ZIndex",
        "*:*, *",
        "PageSource, PageIndex, Offset, Color, TargetName, Property, Value, StartPoint, EndPoint",
        "mc:Ignorable, d:IsDataSource, d:LayoutOverrides, d:IsStaticText",
        "Storyboard.*, From, To, Duration"
    ],
    "FirstLineAttributes": "x:Key, Key, x:Name, Name, Grid.Column, Grid.Row, Header",
    "OrderAttributesByName": false,
    "PutEndingBracketOnNewLine": false,
    "RemoveEndingTagOfEmptyElement": true,
    "SpaceBeforeClosingSlash": true,
    "RootElementLineBreakRule": 0,
    "ReorderVSM": 2,
    "ReorderGridChildren": false,
    "ReorderCanvasChildren": false,
    "ReorderSetters": 0,
    "FormatMarkupExtension": true,
    "NoNewLineMarkupExtensions": "x:Bind, Binding",
    "ThicknessSeparator": 0,
    "ThicknessAttributes": "Margin, Padding, BorderThickness, ThumbnailClipMargin",
    "FormatOnSave": false,
    "CommentPadding": 3,
}`

**Comment by grochocki** [comment] 2017-06-29 08:34
Can you share an example file that has the problem? I tried this configuration in one of my projects, and the namespaces seem to be reordering properly.

**Comment by jur007** [comment] 2017-06-29 08:35
only private

**Comment by jur007** [comment] 2017-06-29 08:40
I sent it to your email.

**Comment by grochocki** [comment] 2017-06-29 09:11
Closing this bug, since more generic issue was uncovered. Thanks for helping to uncover this one!

**Closed by grochocki** 2017-06-29 09:11 UTC
Labels: ~duplicate, ~investigating
