### ISSUE TITLE
DataGrid Header

### ISSUE THREAD

**Issue by itsdeandavidson** [Xavalon/XamlStyler#476] opened 2024-03-21 15:24 UTC
**Describe the bug**
I've recently started using this extension and have come across a few instances whereby the style of a DataGrid's header doesn't show after saving/running the extension. I've narrowed this down to being an issue with something the extension is doing (as when I remove the changed formatting, etc it works) possibly due to the re-arranging of  attributes?

**To Reproduce**
1. When formatting DataGrid's
2. See error

**Comment by mrlacey** [comment] 2024-04-01 18:24
@itsdeandavidson Can you share a repro?

**Comment by itsdeandavidson** [comment] 2024-04-01 18:55
Hey,

Sadly not - working in a private repo.

We've identified that the issue is due to the re-organising of the DataGrid attributes.

**Comment by mrlacey** [comment] 2024-04-01 21:09
> We've identified that the issue is due to the re-organising of the DataGrid attributes.

Yeah, it's disappointing and not always obvious that the order of attributes can affect what gets rendered. Sometimes even causing exceptions. (I remember some Xamarin.Forms controls that would do this too as internal logic was dependent upon the order the properties were set in XAML.)

Can I suggest closing this as not a bug.

**Closed** 2024-04-01 21:49 UTC
Labels: Bug
