### ISSUE TITLE
CLI options `check` `dry-run`

### ISSUE THREAD

**Issue by virzak** [Xavalon/XamlStyler#198] opened 2019-07-17 19:35 UTC
Looking for an option to test that all files are formatted, but the pre-commit hook is being utilized by [husky](https://github.com/typicode/husky).

Would like to have a check / dry run option the same way dotnet format is [doing](https://github.com/dotnet/format#how-to-use) it.

```sh
dotnet format --check --dry-run
```

Is an option like that available?

**Comment by grochocki** [comment] 2019-07-17 20:55
Do you see this as a dupe of #176?

**Comment by virzak** [comment] 2019-07-17 21:25
I do. Glad to see this has been requested already.

**Comment by grochocki** [comment] 2019-07-17 21:28
Cool, going to close this as a duplicate then.

**Closed by grochocki** 2019-07-17 21:28 UTC
Labels: Console, Feature, ~duplicate
