### ISSUE TITLE
Auto formatting expands XAML file

### ISSUE THREAD

**Issue by VicenteCartas** [Xavalon/XamlStyler#126] opened 2017-10-25 20:57 UTC
When working on a file, if there is a save, the styler will run and all the sections in the file will be expanded. Is it possible that we get the code formatted but we maintain the state (collapsed/expanded) of the XAML sections?

**Comment by grochocki** [comment] 2017-10-25 21:08
This is a duplicate of #98, which was fixed in #119. We are working on finalizing a new release, so stay tuned.

**Closed by grochocki** 2017-10-25 21:08 UTC
Labels: Type: Bug, ~duplicate
