### ISSUE TITLE
Make attribute reordering disabled by default

### ISSUE THREAD

**Issue by antoinebj** [Xavalon/XamlStyler#183] opened 2019-04-30 13:14 UTC
Hi,

In my team, we're experiencing #177 but also the loss of the shared settings.
That means that even if we specified a file name with search to root, those settings would be lost too.
It happens on a regular, nearly daily basis.

This issue is not about fixing those problems, but about the fact that when such problems happen due to a regression, the developer who applies formatting will get all attributes in his XAML file re-ordered.
That won't be a problem if the developer usually has settings for reordering, as he can just re-apply formatting once the settings are restored and he'll find his XAML as it was before.
But for those who disable attribute reordering, it creates a huge amount of noise in the file that would make a review impossible. If the developer does not notice it immediately and closes the file, he won't be able to use the Undo command. He'll have to fix XamlStyler settings, revert the file (thanks to source control) and reapply the intended changes.

I propose that the default settings disable attribute reordering. IMHO, in general it would make sense to avoid default settings that have effects that are difficult to reverse.

**Comment by Tyrrrz** [comment] 2020-01-14 08:42
I think attribute reordering should stay default because it's one of the most useful features of the tool.

> IMHO, in general it would make sense to avoid default settings that have effects that are difficult to reverse.

It doesn't sound like a strict metric, aren't all changes easy reverse anyway? Like you pointed out, you just do `git reset`.

**Comment by antoinebj** [comment] 2020-01-14 09:13
> I think attribute reordering should stay default because it's one of the most useful features of the tool.

That's down to preference. In our team, we prefer not to use it, and it we still have other substantial reasons to use that extension.

Also, for those who find that to be the most useful, it will take very little time to activate it. If surprisingly they do forget, it won't mess up existing files, and they can just catch up later by activating it and running the formatting again.

> > IMHO, in general it would make sense to avoid default settings that have effects that are difficult to reverse.
> 
> It doesn't sound like a strict metric, aren't all changes easy to reverse anyway? Like you pointed out, you just do `git reset`.

You might have made a significant number of changes to the file. You don't want to simply `git reset` the file and lose 20 or 30 minutes of work.
And when you work in a team with newcomers, you can't be breathing down their neck all the time, sometimes they end up committing a file that's completely messed up. The diff is then unusable, and finding out what changed and how to re-apply it with the right formatting will take a significant amount of time for a big XAML file.

**Comment by Tyrrrz** [comment] 2020-01-14 09:32
Hm, I see.
As for #177, did you try naming your file `Settings.XamlStyler` and placing it inside the root of the repository?

**Comment by antoinebj** [comment] 2020-01-14 09:41
> As for #177, did you try naming your file `Settings.XamlStyler` and placing it inside the root of the repository?

Yes, that file's been there, named exactly like that, since mid-2017.
I haven't had trouble lately with that, and my colleagues haven't complained about it in a while either.
So I don't know why it happened back then, and what changed in between except the version of Visual Studio.

**Comment by grochocki** [comment] 2020-01-14 19:02
> I think attribute reordering should stay default because it's one of the most useful features of the tool.

> That's down to preference. In our team, we prefer not to use it, and it we still have other substantial reasons to use that extension.

Both true statements but attribute reordering is one of the _key_ features of the extension. From a feature request perspective, I don't think we would consider making this change to the default.

That being said, if there is still a bug someplace in how we are processing external configurations, we should get to the root of that and fix it.

> I haven't had trouble lately with that, and my colleagues haven't complained about it in a while either.

There have been a bunch of bug fixes since 2017. I would recommend trying the [latest version](https://github.com/Xavalon/XamlStyler/releases).

@antoinebj I'd like to close this feature request, since it seems that the root cause is a hard-to-repro bug. Thoughts? If you experience the problem again with the latest version, can you open a new bug with as many details as possible (we have not been able to repro this, which makes it difficult to debug, if it is still a problem).

**Comment by antoinebj** [comment] 2020-01-14 20:00
I still lean towards the most cautious approach to not activate that by default, just like Power Commands does not activate format document and remove & sort usings on save by default.

But I made my point, ultimately it's up to the project maintainers to decide what to do. Either way, it'll still be better than not having the extension at all, and if my team doesn't encounter the loss of configuration again, then it'll be fine.

**Comment by grochocki** [comment] 2020-03-27 06:02
Thanks for the discussion on this one! After reviewing it more closely, we don't think disabling reordering by default is the right move. #95 suggests disabling format by default, which is really similar, but even there, we are not 100% convinced it makes sense to change some of the long-standing defaults.

**Closed by grochocki** 2020-03-27 06:02 UTC
Labels: Feature
