### ISSUE TITLE
Option to align closing bracket with element tag

### ISSUE THREAD

**Issue by tayopi** [Xavalon/XamlStyler#316] opened 2021-01-08 02:09 UTC
**Describe the solution you'd like**
We'd like to have to option to align the closing bracket with the element tag

**Describe alternatives you've considered**
Our current solution is to turn off formatting when saving and changing all of the closing brackets by hand.

**Additional context**
With our current settings our XAML elements look like this:
```xaml
<TextBlock x:Name="simpleTextBlock"
    Margin="4 6 4 8
    FontSize="12"
    Text="Sample Text 1"
    />
```

We would like to have the option to align the closing bracket like this:
```xaml
<TextBlock x:Name="simpleTextBlock"
    Margin="4 6 4 8
    FontSize="12"
    Text="Sample Text 1"
/>
```

**Comment by grochocki** [comment] 2021-01-11 06:22
This appears to be a dupe of #117. As discussed there, this type of styling does not appear to conform to any XAML documentation or large body of code, so it is not something we would be looking to add to XAML Styler at this time.

**Closed by grochocki** 2021-01-11 06:22 UTC
Labels: Feature
