### ISSUE TITLE
Update "Max Attribute Characters Per Line" to apply any time "Attribute Tolerance" is greater than "Max Attributes Per Line"

### ISSUE THREAD

**Issue by dPJinjo** [Xavalon/XamlStyler#140] opened 2018-02-07 20:00 UTC
The documentation for [Max Attribute Characters Per Line](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#max-attribute-characters-per-line) states that 

> This setting only takes effect if Max Attributes Per Line is greater than 1 and Attribute Tolerance is greater than 2.

I would like to allow up to a maximum of 2 attributes per line using Attribute Tolerance, but if that line gets too long fall back to multi-lining using Max Attributes Per Line which I've set to 1. In the case where I have a line like...
`<ContentControl HorizontalContentAlignment="Stretch" VerticalContentAlignment="Stretch" />`
I would like it to multi-line without affecting shorter lines like...
`<local:MyControl x:Name="Control" Mode="Auto" />`

I would like Max Attribute Characters Per Line to affect the first example even though my Max Attributes Per Line and Attribute Tolerance values do not enable this setting.

I would like Max Attribute Characters Per Line to be active any time that Attribute Tolerance is greater than Max Attributes Per line.

**Comment by dPJinjo** [comment] 2018-02-09 18:25
Other examples that I wish would multi-line but are showing up as a single line in my IDE.
`<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">`
`<DoubleAnimationUsingKeyFrames Storyboard.TargetName="Add" Storyboard.TargetProperty="(UIElement.Opacity)">`
`<TextBlock Style="{ThemeResource SubtitleTextBlockStyle}" Text="{x:Bind ViewModel.Version, FallbackValue='[0.0.0.0]'}" />`
`<ItemsControl ItemTemplateSelector="{StaticResource TemplateSelector}" ItemsSource="{x:Bind ViewModel.PlatformProperties}" />`
`<SolidColorBrush x:Key="ApplicationBackgroundThemeBrush" Color="{ThemeResource ApplicationBackgroundColor}" />`
`<EntranceThemeTransition FromHorizontalOffset="30" FromVerticalOffset="0" />`

**Comment by Oliamster** [comment] 2020-04-09 00:43
I'am having a similar issue, in VS2019 I would like to always have Binding for instance, in separate lines. The  Attribute torerance seems to have precedence  on max characters per attribute. 

in my example:
Attribute Tolerance: 4
Max Attribute character per line 40
Max Attribute per line 2. 


`<DataGridCheckBoxColumn Binding="{Binding Path=Checked}" ElementStyle="{StaticResource MaterialDesignDataGridCheckBoxColumnStyle}">`

I'm expecting the properties of this line to break up in tow lines.

**Comment by grochocki** [comment] 2020-04-20 03:58
This appears to be a dupe of #12, which we declined. While column break rules work for most languages, we do no believe they make a lot of sense for markup languages like XAML and believe there are already a number of options to help break out attributes on newlines in a way that works well.

**Closed by grochocki** 2020-04-20 03:58 UTC
Labels: Feature
