### ISSUE TITLE
Format Solution

### ISSUE THREAD

**Issue by amkuchta** [Xavalon/XamlStyler#113] opened 2017-08-06 16:05 UTC
Looking at the Wiki, I see that there are options to apply formatting recursively to a directory via the command prompt - would it be possible to add this to the context menu when right clicking the solution or a folder in the solution explorer? Something along the lines of "XamlStyler" => "Style All XAML", perhaps? Just a thought 😄

**Comment by grochocki** [comment] 2017-08-06 23:20
Thanks for the suggestion! This is a duplicate of #56, though, so going to resolve this issue.

**Closed by grochocki** 2017-08-06 23:20 UTC
Labels: Type: Feature, ~duplicate

**Comment by amkuchta** [comment] 2017-08-09 16:21
@grochocki Thank you!  I tried to do a quick search to prevent a duplicate request, but apparently I used what my wife (lovingly?) refers to as "man-eyes".

Do you have a timeline to completion?  Or perhaps even a plan for pre-releases?

**Comment by grochocki** [comment] 2017-08-10 04:23
No ETA for new features like this one, but I have previously investigated how to go about adding the options to right-click on certain elements in Solution Explorer. From what I recall, it is definitely possible, but I ran into a few bugs that I never got around to working through.
