### ISSUE TITLE
XamlStyler does not show on right click

### ISSUE THREAD

**Issue by Makeshet** [Xavalon/XamlStyler#47] opened 2016-09-25 19:15 UTC
I install XamlStyler 2.2 on VS 2015 and its work fine.
Then it stop to show in the context menu when I right click on a Xaml file.
I uninstall and re install and still cen not get it to show on the right click context menu.
Any clue to this bug?
Thanks
Eliezer Kaplansky

**Comment by NicoVermeir** [comment] 2016-09-26 05:50
are you working in a xamarin forms xaml file by any chance? Forms uses the basic xml editor instead of the xaml editor, the right-click menu is set to appear in the xaml editor

**Comment by Makeshet** [comment] 2016-09-26 08:45
No. A very basic WPF project and very simple XAML file.
What other information you need?

**Comment by NicoVermeir** [comment] 2016-09-26 08:46
does saving the file trigger Xaml Styler?

**Comment by Makeshet** [comment] 2016-09-26 08:47
Yes.

**Comment by escamoteur** [comment] 2016-11-10 12:46
Same problem here but I use Xamarin.Forms

**Comment by NicoVermeir** [comment] 2016-11-10 16:28
it's a known issue for Xamarin Forms. the thing is that forms uses the basic XML editor instead of the XAML editor. We need to find the ID of the XML editor so we can add the command there.

I'm working on it!

**Comment by grochocki** [comment] 2016-12-13 07:07
@Makeshet Was your problem resolved with version2.3? If not, would it be possible to share a minimal repro project so I can reproduce the issue? I am not running into any issues with a new WPF application I created.

**Comment by grochocki** [comment] 2016-12-15 09:31
Since the issue was reported with version 2.2, and we cannot repro with version 2.3, I am going to close this for now. If you continue to experience the problem, please reactivate and add more details.

**Closed by grochocki** 2016-12-15 09:31 UTC
Labels: Type: Bug, ~investigating
