### ISSUE TITLE
[Bug Report] Error when formatting project file

### ISSUE THREAD

**Issue by KaiHuaDou** [Xavalon/XamlStyler#467] opened 2024-02-08 10:31 UTC
I set `"FormatOnSave": true`, Then I try to save the `.csproj` file. It reports a "Error In StylerPackage"

![image](https://github.com/Xavalon/XamlStyler/assets/74781268/d40ba474-fc5f-4a00-b17b-56bb3f7cc5cd)

The XamlStyler should not be actived on `.csproj` file.

**External Configuration**

My `Settings.XamlStyler` File: [Settings.txt](https://github.com/Xavalon/XamlStyler/files/14207742/Settings.txt)

**Version Info**
- OS: Windows 10 22H2
- Visual Studio: Enterprise 2022 (x64) 17.9.0 Preview 5.0
- XAML Styler: 3.2311.2

**Comment by grochocki** [comment] 2024-02-13 01:00
This appears to be a dupe of #448, so resolving as such. Please reopen if you think this might be different.

**Closed by grochocki** 2024-02-13 01:00 UTC
Labels: Bug, ~duplicate, VS2022
