### ISSUE TITLE
XamlStyler not showing in VS for Mac version 8.2 (8.2.0.1105)

### ISSUE THREAD

**Issue by Elisha-Misoi** [Xavalon/XamlStyler#199] opened 2019-07-25 15:24 UTC
I have installed XamlStyler but it doesn't seem to be showing or working in the latest Visual Studio 2019 for Mac version 8.2 (8.2.0.1105).

After the update XamlStyler stopped showing in the xaml editor even after numerous re-installs.

Below is a short GIF:

The plugin is installed:

![vs2](https://user-images.githubusercontent.com/45200891/61886817-139af680-af09-11e9-96b4-4017c26c79dc.gif)

Doesn't seem to show up in editor and shortcut is also not working:

![vs1](https://user-images.githubusercontent.com/45200891/61886877-29a8b700-af09-11e9-95f4-5b875031d373.gif)

**Comment by Saratsin** [comment] 2019-07-25 21:40
OMG they provided the new version again XD
I guess the problem is with the new editor (you can try to switch back to the old editor, if they not deleted this option in preferences).
Have you tried a shortcut (Command+Shift+I)?

**Comment by Elisha-Misoi** [comment] 2019-07-25 23:43
The shortcut 'Command+shift+I' also doesn't work. 
Reverting to the older editor seems to solve the issue.
I guess it's an issue with the new editor.

**Comment by omega1100100** [comment] 2019-07-27 19:19
Please fit it, I also encountered the same error.

**Comment by leszekrogowski** [comment] 2019-07-27 20:22
Where can I find the option for reverting to the old editor?

**Comment by Saratsin** [comment] 2019-07-31 18:23
@leszekrogowski  Here you can disable it
![image](https://user-images.githubusercontent.com/16039381/62237351-72fd7880-b3d9-11e9-9e48-d72f900d6cc6.png)

**Comment by Saratsin** [comment] 2019-07-31 18:26
I've found a quite interesting thing. New editor is compatible in many scenarios with the VS for Windows (they made it some kind of cross-platform). [Here](https://github.com/microsoft/vs-editor-api/tree/master/samples) we have the sample of extension, that works for both Studios and shared code, some kind of cross-platform extensions development. I guess I'll try to make the XAML Styler extension by the same approach, so it will be easier to maintain both extensions platforms. @grochocki , what do you think about it?

**Comment by omega1100100** [comment] 2019-08-08 16:28
@Saratsin I don't know why but I start moving from VS2019 to VS Mac and when I installed XAML Styler, it didn't work. Also, what Batch Format XAML is? I clicked and nothing happens.

![image](https://user-images.githubusercontent.com/34548156/62720380-1bdc5100-ba34-11e9-81e4-f292aa539da0.png)

**Comment by AnthonyLatty** [comment] 2019-08-30 04:00
At the moment the only workaround i have found is to use the `Format Document` shortcut. The only disadvantage i found is the arrangement of XAML properties are not correct, but the XAML is formatted.

**Comment by Saratsin** [comment] 2019-09-22 22:04
And support is back. At least partially)
I didn't find the way how to add Format XAML button to the context menu of editor (it doesn't appear with both options, when new editor is either enabled or disabled).
But it works again with Command+Shift+I shortcut, as well as with Edit/Format Xaml button in tabs.
Also "Batch Format Xaml" option works (it formats all the xaml files inside the project/solution)

I advice to relaunch the Visual Studio for Mac after installing this extension. In my case "Format Xaml" button appeared only after that.

**Comment by grochocki** [comment] 2020-01-11 00:03
Fixed via #246

**Closed by grochocki** 2020-01-11 00:03 UTC
Labels: Bug, VSMAC

**Comment by omega1100100** [comment] 2020-01-11 00:07
@grochocki Why does fixing this bug take so long?

**Comment by grochocki** [comment] 2020-01-11 00:33
I personally do not have regular access to Mac for debugging. @saratsin was a huge help in addressing some of the VS for Mac issues. Unified releases are coming with #231, which should help align updates and bug fixes across all versions.
