### ISSUE TITLE
Need i18n support

### ISSUE THREAD

**Issue by Flithor** [Xavalon/XamlStyler#406] opened 2022-09-05 02:45 UTC
This tool is very powerful, awsome!
But some of my colleagues not good in English, they tell me need translation.
Can you add i18n support? I'm glad contribute to translation.

**Comment by grochocki** [comment] 2023-12-28 20:47
Thanks! Support for additional languages would be a fantastic improvement. Closing this as a dupe of #337 where there is already a bit of discussion this.

**Closed by grochocki** 2023-12-28 20:47 UTC
Labels: Feature
