### ISSUE TITLE
Add Format only selected XAML Option

### ISSUE THREAD

**Issue by joaogomes44033** [Xavalon/XamlStyler#214] opened 2019-10-10 10:15 UTC
Please add the option to format only the selected XAML code.
When you are working with legacy code and people that may be changing the same files as you formating code that does not follow any particular style can cause a lot of confusion if you style the entire file.
Adding this option will ease the pain by styling one block at a time and the code changes will be easy to spot. Otherwise it will be a mess to distinguish between a code change and the formatting.

**Comment by grochocki** [comment] 2019-10-24 00:16
This looks like it is a duplicate of #67. I am going to close this issue so we can focus the conversation on this there.

**Closed by grochocki** 2019-10-24 00:16 UTC
