### ISSUE TITLE
Add "Remove unnecessary panel attached properties" option

### ISSUE THREAD

**Issue by dPJinjo** [Xavalon/XamlStyler#141] opened 2018-02-09 02:08 UTC
Frequently in XAML I see that Grid.Row and/or Grid.Column etc. on elements that aren't children of a Grid. This is usually due to copy-paste or UI updates that forget to remove these assignments. I think it would be very easy for XamlStyler to detect this class of error and remove the unneeded attributes.

**Comment by grochocki** [comment] 2018-03-01 19:26
In my experiences, this has never really been a problem, so I am not 100% sure this makes sense as a standalone option for Grid.* attributes. I do think there is potential for a larger more generic feature that adds an option to remove default properties (e.g., Grid.Row="0"). A system like this could incorporate removing unneeded attributes as well. Thoughts?

**Comment by dPJinjo** [comment] 2018-03-06 17:55
There are other such class of attached DPs for panels that elements aren't a child of, like Canvas.* (Canvas.Left, Canvas.Top) and RelativePanel.* (RelativePanel.AlignLeftWith) (others?). When assigned to elements that aren't children of such panels, these attributes are useless work for XBF and the XAML parser and make markup more verbose and less maintainable. I think "removal of unnecessary panel attached properties" could be a valuable feature.

I do like the idea of removing attributes assignments of default property values. I think this could extend beyond Grid. I always see a lot of <RowDefinition Height="*" /> and Margin="0,0,0,0" in markup.

**Comment by grochocki** [comment] 2018-03-09 00:29
Also created #149. These two features feel like they should be treated separately.

**Comment by grochocki** [comment] 2019-06-23 22:10
I like the idea of including removing unnecessary panel attached properties, but let's discuss including this in #149. Closing as a dupe of that.

**Closed by grochocki** 2019-06-23 22:10 UTC
Labels: Feature, ~duplicate
