### ISSUE TITLE
Setters ordering

### ISSUE THREAD

**Issue by GreenKn1ght** [Xavalon/XamlStyler#104] opened 2017-05-11 16:18 UTC
Would be great to sort setters in style by attribute "Property" in same order like an element's attribute sorting.
Without ordering in large styles difficulty to find specific property or compare styles side-by-side.

**Comment by grochocki** [comment] 2020-04-09 07:09
Closing as a duplicate of #10.

**Closed by grochocki** 2020-04-09 07:09 UTC
Labels: Feature
