### ISSUE TITLE
Single line opening tags with attributes should have option for space before closing bracket

### ISSUE THREAD

**Issue by dPJinjo** [Xavalon/XamlStyler#137] opened 2018-02-03 02:48 UTC
I think `<Button Width="100">` should be `<Button Width="100" >` if "Space before ending slash in self-closing elements" is "True", and the '>' is not on its own line and there are attributes. Effectively this would put a space between the last quote from an attribute and the closing tag '>'.

**Comment by grochocki** [comment] 2018-02-03 21:06
The setting, "Space before ending slash in self-closing elements" describes behavior affecting the "/>" closure of an element, which occurs when it is such that the starting and ending tags are one and the same. From [XAML documentation](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/xaml-syntax-in-detail#object-element-syntax), it is essentially this case:

> The element and tag must be closed by a forward slash (/) followed immediately by a right angle bracket (>).

In this regard, it is by design. However, you could consider this a feature request for a new setting along the lines of "Space before closing bracket of opening tags of elements that contain attributes".

This is incredibly specific, though. `<Button Width="100">` would become `<Button Width="100" >` , but `<Button>` would remain `<Button>`. Closing tags (e.g., `</StackPanel>`), elements utilizing property element syntax (e.g., `<Button.Content>`), and a number of other cases that closing brackets are used would also be unaffected. Arguably, in all those cases, adding a space before the closing bracket would not be considered a generally-accepted formatting. As such, I am leaning towards not accepting the feature request per [contribution guidelines](https://github.com/Xavalon/XamlStyler/blob/master/CONTRIBUTING.md):

> Determine if the feature is a good fit — ask yourself if the feature would benefit most users. Everyone has their own unique style, but we are more likely to accept features that have an impact on a larger number of users.

Happy to open it up to further discussion, though.

**Comment by dPJinjo** [comment] 2018-02-04 21:19
Thanks grochocki. I think you're right that tying this feature request to the "Space before ending slash in self-closing elements" option is confusing and undesired. Changing the title to be more specific is good. I would still like to request that there be an additional option to allow a space space between the last attribute " character and the closing > character for single line tags. I think this option pairs well with the space before closing brackets one visually and will help code diffs appear more succinct.

**Comment by grochocki** [comment] 2020-04-20 03:56
After reviewing this based on our [feature request guidelines](https://github.com/Xavalon/XamlStyler/blob/master/CONTRIBUTING.md#guidelines-for-feature-requests), we feel like this particular request reflects a personal style preference that might not be a good fit for the larger developer community, so we are declining this feature suggestion. Thanks for your contribution!

**Closed by grochocki** 2020-04-20 03:56 UTC
Labels: Feature
