### ISSUE TITLE
Visual Studio SaveAll deadlocks with XamlStyler installed

### ISSUE THREAD

**Issue by paiden** [Xavalon/XamlStyler#174] opened 2019-01-29 06:21 UTC
Sometimes my Visual studio deadlocks when I have XamlStyler installed and invoke the 'Save All' operation.

VS version is VS2019 Preview 2

XamlStylerVersion is 3.2

The callstack when the deadlock happens:

```
WindowsBase.dll!System.Windows.Threading.DispatcherSynchronizationContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)	Unknown
mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 349	C#
[Native to Managed Transition]	
[Managed to Native Transition]	
System.dll!System.ComponentModel.Container.Add(System.ComponentModel.IComponent component, string name) Line 57	C#
System.dll!System.ComponentModel.Container.Add(System.ComponentModel.IComponent component) Line 46	C#
Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Package.GetDialogPage(System.Type dialogPageType)	Unknown
XamlStyler3.Package.dll!Xavalon.XamlStyler3.Package.StylerPackage.OnFileSaveAllBeforeExecute.AnonymousMethod__9_0(EnvDTE.Document document)	Unknown
mscorlib.dll!System.Threading.Tasks.Parallel.ForEachWorker.AnonymousMethod__0(int i) Line 2354	C#
mscorlib.dll!System.Threading.Tasks.Parallel.ForWorker.AnonymousMethod__1() Line 1193	C#
mscorlib.dll!System.Threading.Tasks.Task.InnerInvoke() Line 2884	C#
mscorlib.dll!System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task childTask) Line 2899	C#
mscorlib.dll!System.Threading.Tasks.Task.ExecuteSelfReplicating.AnonymousMethod__0(object value) Line 2624	C#
mscorlib.dll!System.Threading.Tasks.Task.ExecuteSelfReplicating(System.Threading.Tasks.Task root) Line 2694	C#
mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2521	C#
mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2756	C#
mscorlib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued) Line 92	C#
mscorlib.dll!System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued) Line 219	C#
mscorlib.dll!System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler scheduler, bool waitForCompletion) Line 1219	C#
mscorlib.dll!System.Threading.Tasks.Task.RunSynchronously(System.Threading.Tasks.TaskScheduler scheduler) Line 1168	C#
mscorlib.dll!System.Threading.Tasks.Parallel.ForWorker<object>(int fromInclusive, int toExclusive, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action<int> body, System.Action<int, System.Threading.Tasks.ParallelLoopState> bodyWithState, System.Func<int, System.Threading.Tasks.ParallelLoopState, object, object> bodyWithLocal, System.Func<object> localInit, System.Action<object> localFinally) Line 1264	C#
mscorlib.dll!System.Threading.Tasks.Parallel.ForEachWorker<EnvDTE.Document, object>(System.Collections.Generic.IList<EnvDTE.Document> list, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action<EnvDTE.Document> body, System.Action<EnvDTE.Document, System.Threading.Tasks.ParallelLoopState> bodyWithState, System.Action<EnvDTE.Document, System.Threading.Tasks.ParallelLoopState, long> bodyWithStateAndIndex, System.Func<EnvDTE.Document, System.Threading.Tasks.ParallelLoopState, object, object> bodyWithStateAndLocal, System.Func<EnvDTE.Document, System.Threading.Tasks.ParallelLoopState, long, object, object> bodyWithEverything, System.Func<object> localInit, System.Action<object> localFinally) Line 2353	C#
mscorlib.dll!System.Threading.Tasks.Parallel.ForEachWorker<EnvDTE.Document, object>(System.Collections.Generic.IEnumerable<EnvDTE.Document> source, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action<EnvDTE.Document> body, System.Action<EnvDTE.Document, System.Threading.Tasks.ParallelLoopState> bodyWithState, System.Action<EnvDTE.Document, System.Threading.Tasks.ParallelLoopState, long> bodyWithStateAndIndex, System.Func<EnvDTE.Document, System.Threading.Tasks.ParallelLoopState, object, object> bodyWithStateAndLocal, System.Func<EnvDTE.Document, System.Threading.Tasks.ParallelLoopState, long, object, object> bodyWithEverything, System.Func<object> localInit, System.Action<object> localFinally) Line 2258	C#
mscorlib.dll!System.Threading.Tasks.Parallel.ForEach<EnvDTE.Document>(System.Collections.Generic.IEnumerable<EnvDTE.Document> source, System.Action<EnvDTE.Document> body) Line 1674	C#
XamlStyler3.Package.dll!Xavalon.XamlStyler3.Package.StylerPackage.OnFileSaveAllBeforeExecute(string guid, int id, object customIn, object customOut, ref bool cancelDefault)	Unknown
EnvDTE.dll!EnvDTE._dispCommandEvents_SinkHelper.BeforeExecute(string A_1, int A_2, object A_3, object A_4, ref bool A_5)	Unknown
[Native to Managed Transition]	
[Managed to Native Transition]	
[Native to Managed Transition]	
[Managed to Native Transition]	
Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(string verb, object pvaIn, out object pvaOut)	Unknown
Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(object parameter)	Unknown
PresentationFramework.dll!MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource commandSource, bool userInitiated)	Unknown
PresentationFramework.dll!System.Windows.Controls.Primitives.ButtonBase.OnClick()	Unknown
PresentationFramework.dll!System.Windows.Controls.Button.OnClick()	Unknown
PresentationFramework.dll!System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs e)	Unknown
PresentationCore.dll!System.Windows.UIElement.OnMouseLeftButtonUpThunk(object sender, System.Windows.Input.MouseButtonEventArgs e)	Unknown
PresentationCore.dll!System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate genericHandler, object genericTarget)	Unknown
PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)	Unknown
PresentationCore.dll!System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, System.Windows.RoutedEventArgs routedEventArgs)	Unknown
PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)	Unknown
PresentationCore.dll!System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args, System.Windows.RoutedEvent newEvent)	Unknown
PresentationCore.dll!System.Windows.UIElement.OnMouseUpThunk(object sender, System.Windows.Input.MouseButtonEventArgs e)	Unknown
PresentationCore.dll!System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate genericHandler, object genericTarget)	Unknown
PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)	Unknown
PresentationCore.dll!System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, System.Windows.RoutedEventArgs routedEventArgs)	Unknown
PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)	Unknown
PresentationCore.dll!System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args)	Unknown
PresentationCore.dll!System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs args)	Unknown
PresentationCore.dll!System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs args, bool trusted)	Unknown
PresentationCore.dll!System.Windows.Input.InputManager.ProcessStagingArea()	Unknown
PresentationCore.dll!System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs input)	Unknown
PresentationCore.dll!System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport inputReport)	Unknown
PresentationCore.dll!System.Windows.Interop.HwndMouseInputProvider.ReportInput(System.IntPtr hwnd, System.Windows.Input.InputMode mode, int timestamp, System.Windows.Input.RawMouseActions actions, int x, int y, int wheel)	Unknown
PresentationCore.dll!System.Windows.Interop.HwndMouseInputProvider.FilterMessage(System.IntPtr hwnd, MS.Internal.Interop.WindowMessage msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
PresentationCore.dll!System.Windows.Interop.HwndSource.InputFilterMessage(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
```

**Comment by JohnnyWestlake** [comment] 2019-02-01 16:48
+ 1 to this. Quite frustrating when I forget to avoid save all.

**Comment by NicoVermeir** [comment] 2019-03-19 15:24
is this still happening on RC2 ?

**Comment by paiden** [comment] 2019-03-22 12:02
Yes. 

It has nothing to do with being the preview version as far as I can tell. The issue also happened in VS2017. I just catched the stack trace while running VS2019 Preview. 

I probably should have stated so in the initial report.

**Comment by grochocki** [comment] 2019-09-23 08:01
Possibly related to #200

**Comment by grochocki** [comment] 2019-12-02 04:29
Resolving as a dupe of #216 which has repro steps that work for some (though, I cannot repro myself).

**Closed by grochocki** 2019-12-02 04:29 UTC
Labels: Bug, VS2017, VS2019, needs more info
